[general]
context=default
allowguest=no
udpbindaddr=0.0.0.0:5062
transport=udp
srvlookup=yes
disallow=all
allow=ulaw
allow=alaw
directmedia=no
nat=force_rport,comedia

[tablet-template](!)
type=friend
host=dynamic
context=intercom-context
secret=IntercomWachtwoord123!
dtmfmode=rfc2833
qualify=yes

[101](tablet-template)
[102](tablet-template)
[103](tablet-template)
[104](tablet-template)
